app: 
  name: "web_app"
  mode: "dev"
  port: 8080

log:
  level: "debug"
  fileName: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "123456"
  dbname: "sql_demo"
  max_open_conns: 1
  max_idle_conns: 1

redis:
  host: "127.0.0.1"
  port: 6379
  pasword: ""
  db: 0
  pool_size: 20


